DROP TABLE IF EXISTS CLM.CESA_C0B017_STG;
CREATE TABLE CLM.CESA_C0B017_STG WITH (APPENDONLY=TRUE, COMPRESSLEVEL=5, ORIENTATION=COLUMN) AS
(
	SELECT DISTINCT A.CUST_SUBS_ID AS SUBS_ID
		, A.CUST_MDN AS MDN
		, CASE 
			--NON STOP, MAU, MYSF 1-5
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'NON STOP' AND C.SUBS_ID IS NOT NULL AND B.PURCHASE_CHANNEL= 'MYSF' AND (CUST_CLM_SA_68 IS NULL OR CUST_CLM_SA_68 <=10000) THEN 1   
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'NON STOP' AND C.SUBS_ID IS NOT NULL AND B.PURCHASE_CHANNEL= 'MYSF' AND (CUST_CLM_SA_68 > 10000 AND CUST_CLM_SA_68 <=45000) THEN 2	 
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'NON STOP' AND C.SUBS_ID IS NOT NULL AND B.PURCHASE_CHANNEL= 'MYSF' AND (CUST_CLM_SA_68 > 45000 AND CUST_CLM_SA_68 <=70000) THEN 3  
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'NON STOP' AND C.SUBS_ID IS NOT NULL AND B.PURCHASE_CHANNEL= 'MYSF' AND (CUST_CLM_SA_68 > 70000 AND CUST_CLM_SA_68 <=100000)THEN 4  
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'NON STOP' AND C.SUBS_ID IS NOT NULL AND B.PURCHASE_CHANNEL= 'MYSF' AND (CUST_CLM_SA_68 > 100000 )THEN 5
			
			--NON STOP, MAU, NON MYSF 6-10
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'NON STOP' AND C.SUBS_ID IS NOT NULL AND B.PURCHASE_CHANNEL= 'NON MYSF' AND (CUST_CLM_SA_68 IS NULL OR CUST_CLM_SA_68 <=10000) THEN 6 
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'NON STOP' AND C.SUBS_ID IS NOT NULL AND B.PURCHASE_CHANNEL= 'NON MYSF' AND (CUST_CLM_SA_68 > 10000 AND CUST_CLM_SA_68 <=45000) THEN 7	 
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'NON STOP' AND C.SUBS_ID IS NOT NULL AND B.PURCHASE_CHANNEL= 'NON MYSF' AND (CUST_CLM_SA_68 > 45000 AND CUST_CLM_SA_68 <=70000) THEN 8  
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'NON STOP' AND C.SUBS_ID IS NOT NULL AND B.PURCHASE_CHANNEL= 'NON MYSF' AND (CUST_CLM_SA_68 > 70000 AND CUST_CLM_SA_68 <=100000)THEN 9  
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'NON STOP' AND C.SUBS_ID IS NOT NULL AND B.PURCHASE_CHANNEL= 'NON MYSF' AND (CUST_CLM_SA_68 > 100000 )THEN 10
			
			----NON STOP, NON MAU, MYSF 11-15
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'NON STOP' AND C.SUBS_ID IS NULL AND B.PURCHASE_CHANNEL= 'MYSF' AND (CUST_CLM_SA_68 IS NULL OR CUST_CLM_SA_68 <=10000) THEN 11   
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'NON STOP' AND C.SUBS_ID IS NULL AND B.PURCHASE_CHANNEL= 'MYSF' AND (CUST_CLM_SA_68 > 10000 AND CUST_CLM_SA_68 <=45000) THEN 12	 
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'NON STOP' AND C.SUBS_ID IS NULL AND B.PURCHASE_CHANNEL= 'MYSF' AND (CUST_CLM_SA_68 > 45000 AND CUST_CLM_SA_68 <=70000) THEN 13  
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'NON STOP' AND C.SUBS_ID IS NULL AND B.PURCHASE_CHANNEL= 'MYSF' AND (CUST_CLM_SA_68 > 70000 AND CUST_CLM_SA_68 <=100000)THEN 14  
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'NON STOP' AND C.SUBS_ID IS NULL AND B.PURCHASE_CHANNEL= 'MYSF' AND (CUST_CLM_SA_68 > 100000 )THEN 15
			
			----NON STOP, NON MAU, NON MYSF 16-20
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'NON STOP' AND C.SUBS_ID IS NULL AND B.PURCHASE_CHANNEL= 'NON MYSF' AND (CUST_CLM_SA_68 IS NULL OR CUST_CLM_SA_68 <=10000) THEN 16 
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'NON STOP' AND C.SUBS_ID IS NULL AND B.PURCHASE_CHANNEL= 'NON MYSF' AND (CUST_CLM_SA_68 > 10000 AND CUST_CLM_SA_68 <=45000) THEN 17	 
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'NON STOP' AND C.SUBS_ID IS NULL AND B.PURCHASE_CHANNEL= 'NON MYSF' AND (CUST_CLM_SA_68 > 45000 AND CUST_CLM_SA_68 <=70000) THEN 18  
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'NON STOP' AND C.SUBS_ID IS NULL AND B.PURCHASE_CHANNEL= 'NON MYSF' AND (CUST_CLM_SA_68 > 70000 AND CUST_CLM_SA_68 <=100000)THEN 19  
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'NON STOP' AND C.SUBS_ID IS NULL AND B.PURCHASE_CHANNEL= 'NON MYSF' AND (CUST_CLM_SA_68 > 100000 )THEN 20

			--UNL, MAU, MYSF 21-25
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'UNLIMITED' AND C.SUBS_ID IS NOT NULL AND B.PURCHASE_CHANNEL= 'MYSF' AND (CUST_CLM_SA_68 IS NULL OR CUST_CLM_SA_68 <=22500) THEN 21   
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'UNLIMITED' AND C.SUBS_ID IS NOT NULL AND B.PURCHASE_CHANNEL= 'MYSF' AND (CUST_CLM_SA_68 > 22500 AND CUST_CLM_SA_68 <=40000) THEN 22	 
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'UNLIMITED' AND C.SUBS_ID IS NOT NULL AND B.PURCHASE_CHANNEL= 'MYSF' AND (CUST_CLM_SA_68 > 40000 AND CUST_CLM_SA_68 <=60000) THEN 23  
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'UNLIMITED' AND C.SUBS_ID IS NOT NULL AND B.PURCHASE_CHANNEL= 'MYSF' AND (CUST_CLM_SA_68 > 60000 AND CUST_CLM_SA_68 <=80000)THEN 24  
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'UNLIMITED' AND C.SUBS_ID IS NOT NULL AND B.PURCHASE_CHANNEL= 'MYSF' AND (CUST_CLM_SA_68 > 80000 )THEN 25
			
			--UNL, MAU, NON MYSF 26-30
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'UNLIMITED' AND C.SUBS_ID IS NOT NULL AND B.PURCHASE_CHANNEL= 'NON MYSF' AND (CUST_CLM_SA_68 IS NULL OR CUST_CLM_SA_68 <=22500) THEN 26  
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'UNLIMITED' AND C.SUBS_ID IS NOT NULL AND B.PURCHASE_CHANNEL= 'NON MYSF' AND (CUST_CLM_SA_68 > 22500 AND CUST_CLM_SA_68 <=40000) THEN 27	 
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'UNLIMITED' AND C.SUBS_ID IS NOT NULL AND B.PURCHASE_CHANNEL= 'NON MYSF' AND (CUST_CLM_SA_68 > 40000 AND CUST_CLM_SA_68 <=60000) THEN 28  
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'UNLIMITED' AND C.SUBS_ID IS NOT NULL AND B.PURCHASE_CHANNEL= 'NON MYSF' AND (CUST_CLM_SA_68 > 60000 AND CUST_CLM_SA_68 <=80000)THEN 29 
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'UNLIMITED' AND C.SUBS_ID IS NOT NULL AND B.PURCHASE_CHANNEL= 'NON MYSF' AND (CUST_CLM_SA_68 > 80000 )THEN 30
			
			----UNL, NON MAU, MYSF 31-35
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'UNLIMITED' AND C.SUBS_ID IS NULL AND B.PURCHASE_CHANNEL= 'MYSF' AND (CUST_CLM_SA_68 IS NULL OR CUST_CLM_SA_68 <=22500) THEN 31   
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'UNLIMITED' AND C.SUBS_ID IS NULL AND B.PURCHASE_CHANNEL= 'MYSF' AND (CUST_CLM_SA_68 > 22500 AND CUST_CLM_SA_68 <=40000) THEN 32	 
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'UNLIMITED' AND C.SUBS_ID IS NULL AND B.PURCHASE_CHANNEL= 'MYSF' AND (CUST_CLM_SA_68 > 40000 AND CUST_CLM_SA_68 <=60000) THEN 33  
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'UNLIMITED' AND C.SUBS_ID IS NULL AND B.PURCHASE_CHANNEL= 'MYSF' AND (CUST_CLM_SA_68 > 60000 AND CUST_CLM_SA_68 <=80000)THEN 34  
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'UNLIMITED' AND C.SUBS_ID IS NULL AND B.PURCHASE_CHANNEL= 'MYSF' AND (CUST_CLM_SA_68 > 80000 )THEN 35
			
			----UNL, NON MAU, NON MYSF 36-40
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'UNLIMITED' AND C.SUBS_ID IS NULL AND B.PURCHASE_CHANNEL= 'NON MYSF' AND (CUST_CLM_SA_68 IS NULL OR CUST_CLM_SA_68 <=22500) THEN 36  
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'UNLIMITED' AND C.SUBS_ID IS NULL AND B.PURCHASE_CHANNEL= 'NON MYSF' AND (CUST_CLM_SA_68 > 22500 AND CUST_CLM_SA_68 <=40000) THEN 37	 
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'UNLIMITED' AND C.SUBS_ID IS NULL AND B.PURCHASE_CHANNEL= 'NON MYSF' AND (CUST_CLM_SA_68 > 40000 AND CUST_CLM_SA_68 <=60000) THEN 38  
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'UNLIMITED' AND C.SUBS_ID IS NULL AND B.PURCHASE_CHANNEL= 'NON MYSF' AND (CUST_CLM_SA_68 > 60000 AND CUST_CLM_SA_68 <=80000)THEN 39 
			WHEN UPPER (B.PACKAGE_CATEGORY) = 'UNLIMITED' AND C.SUBS_ID IS NULL AND B.PURCHASE_CHANNEL= 'NON MYSF' AND (CUST_CLM_SA_68 > 80000 )THEN 40
			
			--OTHER, MAU, MYSF 41-46
			WHEN UPPER (B.PACKAGE_CATEGORY) IN ('VOLUME','OTHER') AND C.SUBS_ID IS NOT NULL AND B.PURCHASE_CHANNEL= 'MYSF' AND (CUST_CLM_SA_68 IS NULL OR CUST_CLM_SA_68 <=10000) THEN 41   
			WHEN UPPER (B.PACKAGE_CATEGORY) IN ('VOLUME','OTHER') AND C.SUBS_ID IS NOT NULL AND B.PURCHASE_CHANNEL= 'MYSF' AND (CUST_CLM_SA_68 > 10000 AND CUST_CLM_SA_68 <=20000) THEN 42	 
			WHEN UPPER (B.PACKAGE_CATEGORY) IN ('VOLUME','OTHER') AND C.SUBS_ID IS NOT NULL AND B.PURCHASE_CHANNEL= 'MYSF' AND (CUST_CLM_SA_68 > 20000 AND CUST_CLM_SA_68 <=30000) THEN 43  
			WHEN UPPER (B.PACKAGE_CATEGORY) IN ('VOLUME','OTHER') AND C.SUBS_ID IS NOT NULL AND B.PURCHASE_CHANNEL= 'MYSF' AND (CUST_CLM_SA_68 > 30000 AND CUST_CLM_SA_68 <=40000)THEN 44  
			WHEN UPPER (B.PACKAGE_CATEGORY) IN ('VOLUME','OTHER') AND C.SUBS_ID IS NOT NULL AND B.PURCHASE_CHANNEL= 'MYSF' AND (CUST_CLM_SA_68 > 40000 AND CUST_CLM_SA_68 <=60000 )THEN 45
			WHEN UPPER (B.PACKAGE_CATEGORY) IN ('VOLUME','OTHER') AND C.SUBS_ID IS NOT NULL AND B.PURCHASE_CHANNEL= 'MYSF' AND (CUST_CLM_SA_68 > 60000 )THEN 46
			
			--OTHER, MAU, NON MYSF 47-52
			WHEN UPPER (B.PACKAGE_CATEGORY) IN ('VOLUME','OTHER') AND C.SUBS_ID IS NOT NULL AND B.PURCHASE_CHANNEL= 'NON MYSF' AND (CUST_CLM_SA_68 IS NULL OR CUST_CLM_SA_68 <=10000) THEN 47 
			WHEN UPPER (B.PACKAGE_CATEGORY) IN ('VOLUME','OTHER') AND C.SUBS_ID IS NOT NULL AND B.PURCHASE_CHANNEL= 'NON MYSF' AND (CUST_CLM_SA_68 > 10000 AND CUST_CLM_SA_68 <=20000) THEN 48	 
			WHEN UPPER (B.PACKAGE_CATEGORY) IN ('VOLUME','OTHER') AND C.SUBS_ID IS NOT NULL AND B.PURCHASE_CHANNEL= 'NON MYSF' AND (CUST_CLM_SA_68 > 20000 AND CUST_CLM_SA_68 <=30000) THEN 49  
			WHEN UPPER (B.PACKAGE_CATEGORY) IN ('VOLUME','OTHER') AND C.SUBS_ID IS NOT NULL AND B.PURCHASE_CHANNEL= 'NON MYSF' AND (CUST_CLM_SA_68 > 30000 AND CUST_CLM_SA_68 <=40000)THEN 50  
			WHEN UPPER (B.PACKAGE_CATEGORY) IN ('VOLUME','OTHER') AND C.SUBS_ID IS NOT NULL AND B.PURCHASE_CHANNEL= 'NON MYSF' AND (CUST_CLM_SA_68 > 40000 AND CUST_CLM_SA_68 <=60000 )THEN 51
			WHEN UPPER (B.PACKAGE_CATEGORY) IN ('VOLUME','OTHER') AND C.SUBS_ID IS NOT NULL AND B.PURCHASE_CHANNEL= 'NON MYSF' AND (CUST_CLM_SA_68 > 60000 )THEN 52
			
			--OTHER,NON MAU, MYSF 53-58
			WHEN UPPER (B.PACKAGE_CATEGORY) IN ('VOLUME','OTHER') AND C.SUBS_ID IS NULL AND B.PURCHASE_CHANNEL= 'MYSF' AND (CUST_CLM_SA_68 IS NULL OR CUST_CLM_SA_68 <=10000) THEN 53
			WHEN UPPER (B.PACKAGE_CATEGORY) IN ('VOLUME','OTHER') AND C.SUBS_ID IS NULL AND B.PURCHASE_CHANNEL= 'MYSF' AND (CUST_CLM_SA_68 > 10000 AND CUST_CLM_SA_68 <=20000) THEN 54	 
			WHEN UPPER (B.PACKAGE_CATEGORY) IN ('VOLUME','OTHER') AND C.SUBS_ID IS NULL AND B.PURCHASE_CHANNEL= 'MYSF' AND (CUST_CLM_SA_68 > 20000 AND CUST_CLM_SA_68 <=30000) THEN 55  
			WHEN UPPER (B.PACKAGE_CATEGORY) IN ('VOLUME','OTHER') AND C.SUBS_ID IS NULL AND B.PURCHASE_CHANNEL= 'MYSF' AND (CUST_CLM_SA_68 > 30000 AND CUST_CLM_SA_68 <=40000)THEN 56 
			WHEN UPPER (B.PACKAGE_CATEGORY) IN ('VOLUME','OTHER') AND C.SUBS_ID IS NULL AND B.PURCHASE_CHANNEL= 'MYSF' AND (CUST_CLM_SA_68 > 40000 AND CUST_CLM_SA_68 <=60000 )THEN 57
			WHEN UPPER (B.PACKAGE_CATEGORY) IN ('VOLUME','OTHER') AND C.SUBS_ID IS NULL AND B.PURCHASE_CHANNEL= 'MYSF' AND (CUST_CLM_SA_68 > 60000 )THEN 58
			
			--OTHER, NON MAU, NON MYSF 59-64
			WHEN UPPER (B.PACKAGE_CATEGORY) IN ('VOLUME','OTHER') AND C.SUBS_ID IS NULL AND B.PURCHASE_CHANNEL= 'NON MYSF' AND (CUST_CLM_SA_68 IS NULL OR CUST_CLM_SA_68 <=10000) THEN 59 
			WHEN UPPER (B.PACKAGE_CATEGORY) IN ('VOLUME','OTHER') AND C.SUBS_ID IS NULL AND B.PURCHASE_CHANNEL= 'NON MYSF' AND (CUST_CLM_SA_68 > 10000 AND CUST_CLM_SA_68 <=20000) THEN 60	 
			WHEN UPPER (B.PACKAGE_CATEGORY) IN ('VOLUME','OTHER') AND C.SUBS_ID IS NULL AND B.PURCHASE_CHANNEL= 'NON MYSF' AND (CUST_CLM_SA_68 > 20000 AND CUST_CLM_SA_68 <=30000) THEN 61  
			WHEN UPPER (B.PACKAGE_CATEGORY) IN ('VOLUME','OTHER') AND C.SUBS_ID IS NULL AND B.PURCHASE_CHANNEL= 'NON MYSF' AND (CUST_CLM_SA_68 > 30000 AND CUST_CLM_SA_68 <=40000)THEN 62 
			WHEN UPPER (B.PACKAGE_CATEGORY) IN ('VOLUME','OTHER') AND C.SUBS_ID IS NULL AND B.PURCHASE_CHANNEL= 'NON MYSF' AND (CUST_CLM_SA_68 > 40000 AND CUST_CLM_SA_68 <=60000 )THEN 63
			WHEN UPPER (B.PACKAGE_CATEGORY) IN ('VOLUME','OTHER') AND C.SUBS_ID IS NULL AND B.PURCHASE_CHANNEL= 'NON MYSF' AND (CUST_CLM_SA_68 > 60000 )THEN 64

		END AS FLAG
	FROM RPT_CC.V_RPT_DS_CUSTOMER_360 A INNER JOIN CLM.CESA_C0B016_BASE_03 B ON A.CUST_SUBS_ID = B.SUBS_ID
		LEFT JOIN 
		(
			SELECT DISTINCT SUBS_ID
			FROM DWH_CC.F_MYSF_USER_BASE
			WHERE PARTITION_DATE BETWEEN CURRENT_DATE::DATE-31 AND CURRENT_DATE::DATE-1
		)C ON A.CUST_SUBS_ID = C.SUBS_ID
	WHERE 
		UPPER(CUST_SETTLEMENT) = 'PREPAID'
		--- AND COALESCE(CUST_CHURN_RISK_CATEGORY_NEW) LIKE '%HIGH%RISK, %' <BONA> REMOVE
		AND COALESCE(CUST_CHURN_RISK_CATEGORY_NEW) IN ('HIGH - MED RISK', 'HIGH - LOW RISK', 'HIGH - HIGH RISK') --- <BONA> ADD
		AND CUST_CLM_BUCKET_CATEGORY IN ('BUCKET 2','BUCKET 3','BUCKET 4','BUCKET 5') 
		AND UPPER(CUST_CURR_STATUS) IN ('A'/*,'D','E'*/)
		AND COALESCE(CUST_CLM_SA_80,'N') = 'N' 
		AND (UPPER(A.CUST_BUNDLING_DEVICE_MARKET_NAME) NOT LIKE '%SMARTDEAL%' OR A.CUST_BUNDLING_DEVICE_MARKET_NAME IS NULL) 
		AND COALESCE(A.CUST_EMPLOYEE_FLAG,'N')='N'															
		AND COALESCE(A.CUST_PREMIUM_FLAG,'N')='N'						
		AND COALESCE(A.CUST_VIP_FLAG,'N')='N'						
		AND COALESCE(A.CUST_DEALER_FLAG,'N')='N'							
		AND A.CUST_SUBS_ID NOT IN (SELECT SUBS_ID FROM CLM.MCCM_BLACKLIST_NBR WHERE NOTE IS NULL OR (NOTE NOT IN ('New SP 1ON+','Power Up') AND EXPIRED_DATE > CURRENT_DATE)) --BLACKLIST UNTUK CAMPAIGN WOW CASHBACK PROGRAM 
		AND COALESCE(A.CUST_BLACKLIST_POPUP_CAMPAIGN_FLAG,'N')='N'				
		AND COALESCE(A.CUST_SP_LOYALTY_FLAG,'N')='N'						
	    AND A.CUST_MDN NOT IN ('8811217788','8811450084','88212133918') 
		AND COALESCE(A.CUST_FWA_FLAG,'N')='N'							
		AND COALESCE(A.CUST_DUO_FLAG,'N')='N'							
		AND UPPER(COALESCE(A.CUST_DEVICE_TYPE,'N')) NOT LIKE '%TABLET%' 
		AND UPPER(COALESCE(A.CUST_DEVICE_TYPE,'N')) NOT LIKE '%DONGLE%'
		AND UPPER(COALESCE(A.CUST_DEVICE_TYPE,'N')) NOT LIKE '%MIFI%' 
		AND UPPER(COALESCE(A.CUST_DEVICE_TYPE,'N')) NOT LIKE '%MODEM%' 
		AND UPPER(COALESCE(A.CUST_DEVICE_TYPE,'N')) NOT LIKE '%ROUTER%' 
		AND COALESCE(A.CUST_EVO_FLAG,'N')='N' --TERGANTUNG SEGMENT CRITERIA, CONTOH : TIDAK BERLAKU UNTUK CAMPAIGN OFFER DATA	
		AND COALESCE(A.CUST_SMARTCALL_FLAG,'N')='N'						
		AND COALESCE(A.CUST_SMARTREK_FLAG,'N')='N'						
		AND COALESCE(A.CUST_GAME_EXC_FLAG,'N')='N'				
)
DISTRIBUTED BY (SUBS_ID)
;

DROP TABLE IF EXISTS CLM.TEMP_MCCM_SEGMENT_C0B017_TARGET;
CREATE TABLE CLM.TEMP_MCCM_SEGMENT_C0B017_TARGET AS
(
SELECT
	 DISTINCT
	 SUBS_ID
	,FLAG
	,NULL AS PROD_STATE
	,'C0B017' AS CAMPAIGN_CODE
	,CURRENT_DATE::DATE CREATED_DATE
	,CURRENT_DATE::DATE START_DATE
	,CURRENT_DATE::DATE+7 END_DATE 
	,0 AS HOLDOUT
	,0 AS HOLDOUT_TOPUP
	,0 AS HOLDOUT_SEEDING
	,0 AS HOLDOUT_CLM_PACKET
	,0 AS HOLDOUT_MASS_PACKET
	,1 AS HOLDOUT_INFORMATIONAL 
	,0 AS HOLDOUT_VOICE_SMS
	,MDN
	,0 AS MOVE_FLAG
	,9 AS MCCM_VERSION
FROM 
	CLM.CESA_C0B017_STG 
WHERE FLAG > 0
) DISTRIBUTED BY (SUBS_ID);





--------------------------------------------------------------------------------INSERT
insert into clm.mccm_target_datamart
select A.subs_id,A.flag::bigint,A.prod_state,A.campaign_code,A.created_date,A.start_date,A.end_date,A.holdout,A.holdout_topup,A.holdout_seeding,A.holdout_clm_packet,A.holdout_mass_packet,A.holdout_informational,A.holdout_voice_sms,A.mdn,B.bucket_category,B.risk_category,B.rev_l1m,B.customer_rfm_segment,A.move_flag, A.MCCM_VERSION
from CLM.TEMP_MCCM_SEGMENT_C0B017_TARGET A
left join sandbox.clm_cesa_rfm_segmentation B on A.subs_id=B.subs_id;