DROP TABLE IF EXISTS CLM.CESA_C0B018_BASE_01 ;
CREATE TABLE CLM.CESA_C0B018_BASE_01 WITH (APPENDONLY=TRUE, COMPRESSLEVEL=2, ORIENTATION=COLUMN) AS
(
SELECT *
, ROW_NUMBER() OVER (PARTITION BY SUBS_ID ORDER BY PARTITION_DATE DESC) AS RN 
FROM
(
SELECT SUBS_ID
	, PRICE_PLAN_ID
	, PRICE_PLAN_NAME
	, TOTAL_USAGE 
	, PARTITION_DATE
	, EXT_FIELD3 AS PACKAGE
	, PERIOD
FROM RPT_CC.RPT_REVENUE_BY_CHANNEL 
WHERE PARTITION_DATE BETWEEN CURRENT_DATE::DATE -31 AND CURRENT_DATE::DATE-1
AND PRICE_PLAN_ID IN 
	(
	'792035',
	'792033',
	'833096',
	'792031',
	'473026',
	'475025')
AND TOTAL_USAGE > 0
UNION ALL
SELECT SUBS_ID
	, PRICE_PLAN_ID
	, PRICE_PLAN_NAME
	, TOTAL_USAGE 
	, PARTITION_DATE
	, EXT_FIELD3 AS PACKAGE
	, PERIOD
FROM RPT_CC.RPT_REVENUE_BY_CHANNEL 
WHERE PARTITION_DATE BETWEEN CURRENT_DATE::DATE -29 AND CURRENT_DATE::DATE-1
AND PRICE_PLAN_ID IN 
	(
	'838033',
	'832032',
	'833176')
AND TOTAL_USAGE > 0
)X
)
DISTRIBUTED BY (SUBS_ID);


DROP TABLE IF EXISTS CLM.CESA_C0B018_BASE_02 ;
CREATE TABLE CLM.CESA_C0B018_BASE_02 WITH (APPENDONLY=TRUE, COMPRESSLEVEL=2, ORIENTATION=COLUMN) AS
(
	SELECT DISTINCT A.SUBS_ID
		, CASE 
			WHEN PRICE_PLAN_ID = '838033' THEN 1
			WHEN PRICE_PLAN_ID = '832032' THEN 2
			WHEN PRICE_PLAN_ID = '833176' THEN 3
			WHEN PRICE_PLAN_ID = '792035' THEN 4
			WHEN PRICE_PLAN_ID = '792033' THEN 5
			WHEN PRICE_PLAN_ID = '833096' THEN 6
			WHEN PRICE_PLAN_ID = '792031' THEN 7
			WHEN PRICE_PLAN_ID = '473026' THEN 8
			WHEN PRICE_PLAN_ID = '475025' THEN 9
			end as FLAG
		, A.PRICE_PLAN_NAME
		, CASE 
			WHEN (EXP_DATE::DATE BETWEEN CURRENT_DATE::DATE-4 and CURRENT_DATE::DATE-1 )THEN 1
			ELSE 0 END AS EXP_FLAG
	FROM CLM.CESA_C0B018_BASE_01 A
		LEFT JOIN (
					SELECT 
						DISTINCT SUBS_ID
						, TRX_DATE::DATE 
						, EXP_DATE::DATE
						, DEST_DESC
						, VOL_UNL_FLAG
					FROM DWH_CC.F_NON_TRAFFIC 
					WHERE
						TRX_DATE::DATE BETWEEN CURRENT_DATE::DATE-31 AND CURRENT_DATE::DATE-1
					) B ON A.SUBS_ID = B.SUBS_ID AND A.PARTITION_DATE::DATE = TRX_DATE::DATE
	WHERE RN =1
)
DISTRIBUTED BY (SUBS_ID);
;


DROP TABLE IF EXISTS CLM.CESA_C0B018_STG;
CREATE TABLE CLM.CESA_C0B018_STG WITH (APPENDONLY=TRUE, COMPRESSLEVEL=5, ORIENTATION=COLUMN) AS
(
	SELECT DISTINCT A.CUST_SUBS_ID AS SUBS_ID
		, A.CUST_MDN AS MDN
		, B.FLAG
	FROM RPT_CC.V_RPT_DS_CUSTOMER_360 A INNER JOIN CLM.CESA_C0B018_BASE_02 B ON A.CUST_SUBS_ID = B.SUBS_ID
	WHERE 
		B.EXP_FLAG = 1
		AND UPPER(CUST_SETTLEMENT) = 'PREPAID'
		AND COALESCE(CUST_CHURN_RISK_CATEGORY_NEW)= 'LOW RISK'
		AND CUST_CLM_BUCKET_CATEGORY IN ('BUCKET 2','BUCKET 3','BUCKET 4','BUCKET 5') 
		AND UPPER(CUST_CURR_STATUS) IN ('A'/*,'D','E'*/)
		AND COALESCE(CUST_CLM_SA_80,'N') = 'N' 
		AND (UPPER(A.CUST_BUNDLING_DEVICE_MARKET_NAME) NOT LIKE '%SMARTDEAL%' OR A.CUST_BUNDLING_DEVICE_MARKET_NAME IS NULL) 
		AND COALESCE(A.CUST_EMPLOYEE_FLAG,'N')='N'															
		AND COALESCE(A.CUST_PREMIUM_FLAG,'N')='N'						
		AND COALESCE(A.CUST_VIP_FLAG,'N')='N'						
		AND COALESCE(A.CUST_DEALER_FLAG,'N')='N'							
		AND A.CUST_SUBS_ID NOT IN (SELECT SUBS_ID FROM CLM.MCCM_BLACKLIST_NBR WHERE NOTE IS NULL OR (NOTE NOT IN ('New SP 1ON+','Power Up') AND EXPIRED_DATE > CURRENT_DATE)) --BLACKLIST UNTUK CAMPAIGN WOW CASHBACK PROGRAM 
		AND COALESCE(A.CUST_BLACKLIST_POPUP_CAMPAIGN_FLAG,'N')='N'				
		AND COALESCE(A.CUST_SP_LOYALTY_FLAG,'N')='N'						
	    AND A.CUST_MDN NOT IN ('8811217788','8811450084','88212133918') 
		AND COALESCE(A.CUST_FWA_FLAG,'N')='N'							
		AND COALESCE(A.CUST_DUO_FLAG,'N')='N'							
		AND UPPER(COALESCE(A.CUST_DEVICE_TYPE,'N')) NOT LIKE '%TABLET%' 
		AND UPPER(COALESCE(A.CUST_DEVICE_TYPE,'N')) NOT LIKE '%DONGLE%'
		AND UPPER(COALESCE(A.CUST_DEVICE_TYPE,'N')) NOT LIKE '%MIFI%' 
		AND UPPER(COALESCE(A.CUST_DEVICE_TYPE,'N')) NOT LIKE '%MODEM%' 
		AND UPPER(COALESCE(A.CUST_DEVICE_TYPE,'N')) NOT LIKE '%ROUTER%' 
		AND COALESCE(A.CUST_EVO_FLAG,'N')='N' --TERGANTUNG SEGMENT CRITERIA, CONTOH : TIDAK BERLAKU UNTUK CAMPAIGN OFFER DATA	
		AND COALESCE(A.CUST_SMARTCALL_FLAG,'N')='N'						
		AND COALESCE(A.CUST_SMARTREK_FLAG,'N')='N'						
		AND COALESCE(A.CUST_GAME_EXC_FLAG,'N')='N'				
)
DISTRIBUTED BY (SUBS_ID)
;


DROP TABLE IF EXISTS CLM.TEMP_MCCM_SEGMENT_C0B018_TARGET;
CREATE TABLE CLM.TEMP_MCCM_SEGMENT_C0B018_TARGET AS
(
SELECT
	 DISTINCT
	 SUBS_ID
	,FLAG
	,NULL AS PROD_STATE
	,'C0B018' AS CAMPAIGN_CODE
	,CURRENT_DATE::DATE CREATED_DATE
	,CURRENT_DATE::DATE START_DATE
	,CURRENT_DATE::DATE+3 END_DATE 
	,0 AS HOLDOUT
	,0 AS HOLDOUT_TOPUP
	,0 AS HOLDOUT_SEEDING
	,0 AS HOLDOUT_CLM_PACKET
	,0 AS HOLDOUT_MASS_PACKET
	,1 AS HOLDOUT_INFORMATIONAL 
	,0 AS HOLDOUT_VOICE_SMS
	,MDN
	,0 AS MOVE_FLAG
	,9 AS MCCM_VERSION
FROM 
	CLM.CESA_C0B018_STG 
WHERE FLAG > 0
) DISTRIBUTED BY (SUBS_ID);



--------------------------------------------------------------------------------INSERT
insert into clm.mccm_target_datamart
select A.subs_id,A.flag::bigint,A.prod_state,A.campaign_code,A.created_date,A.start_date,A.end_date,A.holdout,A.holdout_topup,A.holdout_seeding,A.holdout_clm_packet,A.holdout_mass_packet,A.holdout_informational,A.holdout_voice_sms,A.mdn,B.bucket_category,B.risk_category,B.rev_l1m,B.customer_rfm_segment,A.move_flag, A.MCCM_VERSION
from CLM.TEMP_MCCM_SEGMENT_C0B018_TARGET A
left join sandbox.clm_cesa_rfm_segmentation B on A.subs_id=B.subs_id;