DROP TABLE IF EXISTS CLM.CESA_C0B019_STG;
CREATE TABLE CLM.CESA_C0B019_STG WITH (APPENDONLY=TRUE, COMPRESSLEVEL=5, ORIENTATION=COLUMN) AS
(
	SELECT DISTINCT A.CUST_SUBS_ID AS SUBS_ID
		, A.CUST_MDN AS MDN
		, B.FLAG
	FROM RPT_CC.V_RPT_DS_CUSTOMER_360 A INNER JOIN CLM.CESA_C0B018_BASE_02 B ON A.CUST_SUBS_ID = B.SUBS_ID
	WHERE 
		B.EXP_FLAG = 1
		AND UPPER(CUST_SETTLEMENT) = 'PREPAID'
		AND COALESCE(CUST_CHURN_RISK_CATEGORY_NEW) IN ('HIGH - MED RISK', 'HIGH - LOW RISK', 'HIGH - HIGH RISK')
		AND CUST_CLM_BUCKET_CATEGORY IN ('BUCKET 2','BUCKET 3','BUCKET 4','BUCKET 5') 
		AND UPPER(CUST_CURR_STATUS) IN ('A'/*,'D','E'*/)
		AND COALESCE(CUST_CLM_SA_80,'N') = 'N' 
		AND (UPPER(A.CUST_BUNDLING_DEVICE_MARKET_NAME) NOT LIKE '%SMARTDEAL%' OR A.CUST_BUNDLING_DEVICE_MARKET_NAME IS NULL) 
		AND COALESCE(A.CUST_EMPLOYEE_FLAG,'N')='N'															
		AND COALESCE(A.CUST_PREMIUM_FLAG,'N')='N'						
		AND COALESCE(A.CUST_VIP_FLAG,'N')='N'						
		AND COALESCE(A.CUST_DEALER_FLAG,'N')='N'							
		AND A.CUST_SUBS_ID NOT IN (SELECT SUBS_ID FROM CLM.MCCM_BLACKLIST_NBR WHERE NOTE IS NULL OR (NOTE NOT IN ('New SP 1ON+','Power Up') AND EXPIRED_DATE > CURRENT_DATE)) --BLACKLIST UNTUK CAMPAIGN WOW CASHBACK PROGRAM 
		AND COALESCE(A.CUST_BLACKLIST_POPUP_CAMPAIGN_FLAG,'N')='N'				
		AND COALESCE(A.CUST_SP_LOYALTY_FLAG,'N')='N'						
	    AND A.CUST_MDN NOT IN ('8811217788','8811450084','88212133918') 
		AND COALESCE(A.CUST_FWA_FLAG,'N')='N'							
		AND COALESCE(A.CUST_DUO_FLAG,'N')='N'							
		AND UPPER(COALESCE(A.CUST_DEVICE_TYPE,'N')) NOT LIKE '%TABLET%' 
		AND UPPER(COALESCE(A.CUST_DEVICE_TYPE,'N')) NOT LIKE '%DONGLE%'
		AND UPPER(COALESCE(A.CUST_DEVICE_TYPE,'N')) NOT LIKE '%MIFI%' 
		AND UPPER(COALESCE(A.CUST_DEVICE_TYPE,'N')) NOT LIKE '%MODEM%' 
		AND UPPER(COALESCE(A.CUST_DEVICE_TYPE,'N')) NOT LIKE '%ROUTER%' 
		AND COALESCE(A.CUST_EVO_FLAG,'N')='N' --TERGANTUNG SEGMENT CRITERIA, CONTOH : TIDAK BERLAKU UNTUK CAMPAIGN OFFER DATA	
		AND COALESCE(A.CUST_SMARTCALL_FLAG,'N')='N'						
		AND COALESCE(A.CUST_SMARTREK_FLAG,'N')='N'						
		AND COALESCE(A.CUST_GAME_EXC_FLAG,'N')='N'				
)
DISTRIBUTED BY (SUBS_ID)
;


DROP TABLE IF EXISTS CLM.TEMP_MCCM_SEGMENT_C0B019_TARGET;
CREATE TABLE CLM.TEMP_MCCM_SEGMENT_C0B019_TARGET AS
(
SELECT
	 DISTINCT
	 SUBS_ID
	,FLAG
	,NULL AS PROD_STATE
	,'C0B019' AS CAMPAIGN_CODE
	,CURRENT_DATE::DATE CREATED_DATE
	,CURRENT_DATE::DATE START_DATE
	,CURRENT_DATE::DATE+3 END_DATE 
	,0 AS HOLDOUT
	,0 AS HOLDOUT_TOPUP
	,0 AS HOLDOUT_SEEDING
	,0 AS HOLDOUT_CLM_PACKET
	,0 AS HOLDOUT_MASS_PACKET
	,1 AS HOLDOUT_INFORMATIONAL 
	,0 AS HOLDOUT_VOICE_SMS
	,MDN
	,0 AS MOVE_FLAG
	,9 AS MCCM_VERSION
FROM 
	CLM.CESA_C0B019_STG 
WHERE FLAG > 0
) DISTRIBUTED BY (SUBS_ID);


--------------------------------------------------------------------------------INSERT
insert into clm.mccm_target_datamart
select A.subs_id,A.flag::bigint,A.prod_state,A.campaign_code,A.created_date,A.start_date,A.end_date,A.holdout,A.holdout_topup,A.holdout_seeding,A.holdout_clm_packet,A.holdout_mass_packet,A.holdout_informational,A.holdout_voice_sms,A.mdn,B.bucket_category,B.risk_category,B.rev_l1m,B.customer_rfm_segment,A.move_flag, A.MCCM_VERSION
from CLM.TEMP_MCCM_SEGMENT_C0B019_TARGET A
left join sandbox.clm_cesa_rfm_segmentation B on A.subs_id=B.subs_id;